name: desafio-pipeline

on:
  push:
    branches: [ main ]

jobs:
  homologacao:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
      with:
        name: deploy
        path: index.html

  deploy:
    runs-on: ubuntu-latest
    needs: homologacao
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_EC2_METADATA_DISABLED: true
      BUCKET_HOMOLOGACAO: ${{ vars.BUCKET_HOMOLOGACAO }}
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: deploy
        path: index.html
    - run: aws s3 cp index.html s3://$BUCKET_HOMOLOGACAO --recursive --acl public-read
