name: steps examples

on:
	push

jobs:
	jobx:
		runs-on: ubuntu-latest
		steps:
			- name: configuração do node (pesquisar no marketplace...)
				uses: actions/setup-node@v4
			- name: verification of node version
				run: node --version
